name: MortisDualWield
version: '${project.version}'
main: com.mortisdevelopment.mortisdualwield.MortisDualWield
api-version: 1.13
depend:
  - WeaponMechanics
permissions:
  mortisdualwield.reload:
    description: Allows you to use /mortisdualwield reload command
    default: false
commands:
  dualwield:
    aliases:
      - mortisdualwield
